name: Server Bug Report
description: Нашли баг на сервере? Пожалуйста, опишите его.
title: "[SERVER]"
labels: ["bug"]
assignees: ipiepiepie

body:
  - type: textarea
    id: what-happened
    attributes:
      label: Опишите баг
      description: Четкое описание ошибки. Можете углубиться до деталей.
    validations:
      required: true
  - type: textarea
    id: how-happened
    atributes:
      label: Шаги воспроизведения
      description: Опишите, как воспроизвести эту ошибку.
      placeholder: |
        1. Перейдите на '...'
        2. Нажмите на '....'
        3. Дойдите до '....'
        4. Увидите ошибку.
  - markdown:
    attributes:
      value: |
        ### Поведение системы
  - type: input
    id: what-I-see
    attributes:
      label: Фактический результат
      description: Четкое и краткое описание того, что произошло
    validations:
      required: true
  - type: input
    id: what-should-I-see
    attributes:
      label: Ожидаемый результат
      description: Четкое и краткое описание того, что Вы ожидали.
    validations:
      required: true
  - type: input
    id: screenshot
    attributes:
      label: Скриншоты
      description: Если применимо, добавьте снимки экрана, чтобы объяснить вашу проблему.
      placeholder: Вставьте сюда скриншоты
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Версия игры
      description: На какой версии игры это произошло?
    options:
      - 1.12.x
      - 1.13.x
      - 1.14.x
      - 1.15.x
      - 1.16.x
      - 1.17.x
      - 1.18.x
    validations:
      required: true
